const categories = [['🍛','Indian'],['🍕','Pizza'],['🍔','Burgers'],['🍜','Asian'],['🥗','Healthy'],['🍰','Desserts'],['☕','Cafe']];
let restaurants = [];
let cart = JSON.parse(localStorage.getItem('tastekart-cart') || localStorage.getItem('taskekart-cart') || '[]');
if (cart.some(item => !item.restaurantId)) cart = [];
const $ = selector => document.querySelector(selector);
const money = value => `₹${Number(value).toLocaleString('en-IN')}`;
const authToken = () => localStorage.getItem('tastekart-auth-token') || '';
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function saveCart() { localStorage.setItem('tastekart-cart', JSON.stringify(cart)); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => el.classList.remove('show'), 2400); }
function renderCategories() { $('#categoryRow').innerHTML = categories.map(([emoji, name]) => `<button class="category" data-category="${name}"><span class="emoji">${emoji}</span><span>${name}</span></button>`).join(''); document.querySelectorAll('.category').forEach(button => button.onclick = () => toast(`${button.dataset.category} picks coming up`)); }
function renderRestaurants() { $('#restaurantGrid').innerHTML = restaurants.length ? restaurants.map(restaurant => `<article class="restaurant-card ${restaurant.is_open === false ? 'restaurant-closed' : ''}"><div class="restaurant-image" style="background-image:url('${restaurant.image_url || 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80'}')"><span class="offer-tag">${restaurant.is_open === false ? 'CLOSED NOW' : (restaurant.offer || 'FRESH TODAY')}</span></div><div class="restaurant-info"><h3>${escapeHtml(restaurant.name)}</h3><p>${escapeHtml(restaurant.cuisine)}</p><div class="restaurant-meta"><span class="rating">★ ${restaurant.rating ? restaurant.rating : 'New'}</span><span>◷ ${escapeHtml(restaurant.delivery_minutes)}</span></div><button class="menu-button" data-restaurant="${restaurant.id}" ${restaurant.is_open === false ? 'disabled' : ''}>${restaurant.is_open === false ? 'Currently closed' : 'View menu'} <span>→</span></button></div></article>`).join('') : '<div class="empty-cart">No restaurants are available yet.</div>'; document.querySelectorAll('.menu-button:not([disabled])').forEach(button => button.onclick = () => openMenu(button.dataset.restaurant)); }
function dishVisual(item, className = 'menu-emoji') { return item.image_url ? `<span class="${className} has-image"><img src="${escapeHtml(item.image_url)}" alt="${escapeHtml(item.name)}"/><span class="image-fallback">${escapeHtml(item.emoji || '🍽️')}</span></span>` : `<span class="${className}">${escapeHtml(item.emoji || '🍽️')}</span>`; }
function openMenu(id) { const restaurant = restaurants.find(item => item.id === id); $('#menuTitle').textContent = restaurant.name; $('#menuSubtitle').textContent = `${restaurant.cuisine} · ${restaurant.delivery_minutes}`; $('#menuItems').innerHTML = (restaurant.menu || []).map(item => `<div class="menu-item">${dishVisual(item)}<div><h4>${escapeHtml(item.name)}</h4><p>${money(item.price)} · freshly prepared</p></div><button class="menu-add" data-item="${item.id}">Add +</button></div>`).join('') || '<div class="empty-cart">This restaurant is preparing its menu.</div>'; document.querySelectorAll('.menu-add').forEach(button => button.onclick = () => addItem(restaurant, Number(button.dataset.item))); document.querySelectorAll('.menu-emoji img').forEach(image => image.onerror = () => { image.hidden = true; image.nextElementSibling.hidden = false; }); document.querySelectorAll('.image-fallback').forEach(fallback => fallback.hidden = true); $('#menuModal').classList.add('open'); }
function addItem(restaurant, itemId) { const item = (restaurant.menu || []).find(entry => entry.id === itemId); if (cart.length && cart[0].restaurantId !== restaurant.id) return toast('Please finish your current restaurant order first'); const existing = cart.find(entry => entry.id === itemId); if (existing) existing.qty++; else cart.push({id:item.id, name:item.name, price:item.price, emoji:item.emoji, image_url:item.image_url, restaurant:restaurant.name, restaurantId:restaurant.id, qty:1}); saveCart(); renderCart(); toast(`${item.name} added to cart`); }
function renderCart() { const count = cart.reduce((sum, item) => sum + item.qty, 0); const subtotal = cart.reduce((sum, item) => sum + item.price * item.qty, 0); const fee = subtotal ? 29 : 0; $('#cartCount').textContent = count; $('#floatingCount').textContent = count; $('#floatingTotal').textContent = money(subtotal); $('#subtotal').textContent = money(subtotal); $('#deliveryFee').textContent = money(fee); $('#total').textContent = money(subtotal + fee); $('#cartItems').innerHTML = cart.length ? cart.map((item, index) => `<div class="cart-row">${dishVisual(item, 'cart-thumb')}<div><h4>${escapeHtml(item.name)}</h4><p>${escapeHtml(item.restaurant)} · ${money(item.price)}</p></div><div class="qty"><button data-minus="${index}">−</button><span>${item.qty}</span><button data-plus="${index}">+</button></div></div>`).join('') : '<div class="empty-cart">Your cart is waiting for something delicious.<br/>Add a dish to get started.</div>'; document.querySelectorAll('.cart-thumb img').forEach(image => image.onerror = () => { image.hidden = true; image.nextElementSibling.hidden = false; }); document.querySelectorAll('.cart-thumb .image-fallback').forEach(fallback => fallback.hidden = true); document.querySelectorAll('[data-minus]').forEach(button => button.onclick = () => changeQty(+button.dataset.minus, -1)); document.querySelectorAll('[data-plus]').forEach(button => button.onclick = () => changeQty(+button.dataset.plus, 1)); }
function changeQty(index, delta) { cart[index].qty += delta; if (cart[index].qty < 1) cart.splice(index, 1); saveCart(); renderCart(); }
function openCart() { $('#cartDrawer').classList.add('open'); $('#scrim').classList.add('open'); }
function closeCart() { $('#cartDrawer').classList.remove('open'); $('#scrim').classList.remove('open'); }
function closeMenu() { $('#menuModal').classList.remove('open'); }
async function checkout() { if (!cart.length) return toast('Add something tasty first'); if (!authToken()) { closeCart(); authModal(); return toast('Please log in before placing an order'); } try { const response = await fetch('/api/orders', {method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${authToken()}`},body:JSON.stringify({items:cart.map(item => ({id:item.id,quantity:item.qty}))})}); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Order failed'); await fetch(`/api/payments/${data.order.id}`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method:'upi'})}); cart = []; saveCart(); renderCart(); closeCart(); toast(`Order ${data.order.id} confirmed · arriving in ${data.order.eta}`); } catch (error) { toast(error.message); } }
function authModal() { if ($('#authModal')) return $('#authModal').classList.add('open'); document.body.insertAdjacentHTML('beforeend', `<div class="auth-modal open" id="authModal"><div class="auth-card"><button class="close-btn" id="closeAuth">×</button><span class="kicker">TASTEKART ACCOUNT</span><h2 id="authTitle">Welcome back</h2><p id="authMessage">Log in to save your details and track orders.</p><form id="authForm"><input id="authName" placeholder="Your name"/><input id="authEmail" required placeholder="Username or email"/><input id="authPassword" type="password" required minlength="6" placeholder="Password (6+ characters)"/><button class="primary-btn full" type="submit">Log in <span>→</span></button></form><button class="auth-switch" id="authSwitch">New here? Create an account</button></div></div>`); let register = false; const title = $('#authTitle'); const name = $('#authName'); const form = $('#authForm'); $('#closeAuth').onclick = () => $('#authModal').classList.remove('open'); $('#authSwitch').onclick = () => { register = !register; title.textContent = register ? 'Create your account' : 'Welcome back'; name.hidden = !register; name.required = register; form.querySelector('button').innerHTML = register ? 'Create account <span>→</span>' : 'Log in <span>→</span>'; $('#authSwitch').textContent = register ? 'Already have an account? Log in' : 'New here? Create an account'; }; name.hidden = true; form.onsubmit = async event => { event.preventDefault(); try { const endpoint = register ? '/api/auth/register' : '/api/auth/login'; const response = await fetch(endpoint, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.value,username:$('#authEmail').value,password:$('#authPassword').value})}); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to authenticate'); if (register) { register = false; title.textContent = 'Welcome back'; name.hidden = true; name.required = false; form.querySelector('button').innerHTML = 'Log in <span>→</span>'; $('#authSwitch').textContent = 'New here? Create an account'; $('#authMessage').textContent = data.message || 'Account created. Please log in to continue.'; $('#authPassword').value = ''; toast('Account created — please log in'); return; } localStorage.setItem('tastekart-auth-token', data.token); localStorage.setItem('tastekart-user-id', data.user.id); localStorage.setItem('tastekart-user-name', data.user.name); $('#authModal').classList.remove('open'); $('#profileName').textContent = data.user.name; $('#profileInitial').textContent = data.user.name[0].toUpperCase(); toast('Welcome back'); } catch (error) { $('#authMessage').textContent = error.message; } }; }
$('#closeMenu').onclick = closeMenu; $('#menuModal').onclick = event => { if (event.target.id === 'menuModal') closeMenu(); }; $('#openCart').onclick = openCart; $('#closeCart').onclick = closeCart; $('#scrim').onclick = closeCart; $('#checkoutButton').onclick = checkout; $('#profileButton').onclick = openProfile; $('#viewAllCategories').onclick = () => toast('You are already seeing our top picks');
async function loadRestaurants() { try { const response = await fetch('/api/restaurants'); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load restaurants'); restaurants = data.restaurants; renderRestaurants(); } catch (error) { toast(error.message); } }
async function restoreCustomerSession() { if (!authToken()) return authModal(); try { const response = await fetch('/api/auth/me', {headers:{'Authorization':`Bearer ${authToken()}`}}); if (!response.ok) throw new Error('Session expired'); const data = await response.json(); const account = data.account; $('#profileName').textContent = account.name; $('#profileInitial').textContent = account.name[0].toUpperCase(); } catch (_error) { localStorage.removeItem('tastekart-auth-token'); localStorage.removeItem('tastekart-user-id'); localStorage.removeItem('tastekart-user-name'); authModal(); } }
async function openProfile() { if (!authToken()) return authModal(); if ($('#profileModal')) { $('#profileModal').classList.add('open'); return; } document.body.insertAdjacentHTML('beforeend', `<div class="profile-modal open" id="profileModal"><div class="profile-card"><div class="drawer-head"><div><span class="kicker">YOUR TASTEKART ACCOUNT</span><h2>Profile</h2></div><button class="close-btn" id="closeProfile">×</button></div><div id="profileDetails" class="profile-details">Loading your account…</div><div class="profile-orders"><span class="kicker">ORDER HISTORY</span><div id="profileOrders">Loading your orders…</div></div><button id="profileLogout" class="auth-switch">Log out</button></div></div>`); $('#closeProfile').onclick = () => $('#profileModal').classList.remove('open'); $('#profileModal').onclick = event => { if (event.target.id === 'profileModal') $('#profileModal').classList.remove('open'); }; $('#profileLogout').onclick = async () => { await fetch('/api/auth/logout', {method:'POST',headers:{'Authorization':`Bearer ${authToken()}`}}); localStorage.removeItem('tastekart-auth-token'); localStorage.removeItem('tastekart-user-id'); localStorage.removeItem('tastekart-user-name'); $('#profileModal').remove(); $('#profileName').textContent = 'Log in'; $('#profileInitial').textContent = '?'; toast('You have been logged out'); authModal(); }; try { const headers = {'Authorization':`Bearer ${authToken()}`}; const [accountResponse, ordersResponse] = await Promise.all([fetch('/api/auth/me', {headers}), fetch('/api/orders', {headers})]); if (!accountResponse.ok || !ordersResponse.ok) throw new Error('Session expired'); const account = (await accountResponse.json()).account; const orderRows = (await ordersResponse.json()).orders; $('#profileDetails').innerHTML = `<div class="profile-avatar">${escapeHtml(account.name[0].toUpperCase())}</div><div><h3>${escapeHtml(account.name)}</h3><p>${escapeHtml(account.username || account.email || '')}</p><p>${escapeHtml(account.address || 'Address not added')}</p></div>`; $('#profileOrders').innerHTML = orderRows.length ? orderRows.map(order => `<div class="profile-order"><div><strong>${escapeHtml(order.id)}</strong><span>${escapeHtml(order.status)}</span></div><p>${order.items.map(item => `${escapeHtml(item.name)} × ${item.quantity}`).join(', ')}</p><b>${money(order.total)}</b></div>`).join('') : '<p class="profile-empty">No orders yet. Your delicious history starts here.</p>'; } catch (error) { $('#profileDetails').textContent = error.message; $('#profileOrders').textContent = ''; } }
function customerFoodMark(item) { const nonVeg = item.food_type === 'non-veg'; return `<span class="food-mark ${nonVeg ? 'non-veg' : 'veg'}" title="${nonVeg ? 'Non-vegetarian' : 'Vegetarian'}" aria-label="${nonVeg ? 'Non-vegetarian' : 'Vegetarian'}"></span>`; }
function openMenu(id) { const restaurant = restaurants.find(item => item.id === id); $('#menuTitle').textContent = restaurant.name; $('#menuSubtitle').textContent = `${restaurant.cuisine} · ${restaurant.delivery_minutes}`; $('#menuItems').innerHTML = (restaurant.menu || []).map(item => `<div class="menu-item">${dishVisual(item)}<div><h4>${escapeHtml(item.name)} ${customerFoodMark(item)}</h4><p>${money(item.price)} · freshly prepared</p></div><button class="menu-add" data-item="${item.id}">Add +</button></div>`).join('') || '<div class="empty-cart">This restaurant is preparing its menu.</div>'; document.querySelectorAll('.menu-add').forEach(button => button.onclick = () => addItem(restaurant, Number(button.dataset.item))); document.querySelectorAll('.menu-emoji img').forEach(image => image.onerror = () => { image.hidden = true; image.nextElementSibling.hidden = false; }); document.querySelectorAll('.image-fallback').forEach(fallback => fallback.hidden = true); $('#menuModal').classList.add('open'); }
const foodMarkStyle = document.createElement('style'); foodMarkStyle.textContent = '.food-mark{display:inline-grid;place-items:center;width:16px;height:16px;margin-left:6px;border:1px solid currentColor;border-radius:3px;vertical-align:middle}.food-mark:after{content:"";display:block}.food-mark.veg{color:#4c8059}.food-mark.veg:after{width:7px;height:7px;border-radius:50%;background:currentColor}.food-mark.non-veg{color:#c74632}.food-mark.non-veg:after{width:0;height:0;border-left:4px solid transparent;border-right:4px solid transparent;border-bottom:8px solid currentColor}'; document.head.appendChild(foodMarkStyle);
renderCategories(); renderCart(); loadRestaurants(); restoreCustomerSession();
function syncMenuQuantities(){document.querySelectorAll('.menu-add').forEach(button=>{const itemId=Number(button.dataset.item),entry=cart.find(item=>item.id===itemId);if(entry)button.outerHTML=`<div class="menu-qty" data-menu-item="${itemId}"><button data-menu-minus="${itemId}" aria-label="Decrease quantity">−</button><strong>${entry.qty}</strong><button data-menu-plus="${itemId}" aria-label="Increase quantity">+</button></div>`});document.querySelectorAll('.menu-qty').forEach(control=>{const itemId=Number(control.dataset.menuItem),entry=cart.find(item=>item.id===itemId);if(entry)control.querySelector('strong').textContent=entry.qty;else control.outerHTML=`<button class="menu-add" data-item="${itemId}">Add +</button>`})}
document.addEventListener('click',event=>{const target=event.target,menuButton=target.closest('.menu-button'),addButton=target.closest('.menu-add'),minus=target.closest('[data-menu-minus]'),plus=target.closest('[data-menu-plus]');if(menuButton||addButton)setTimeout(syncMenuQuantities,0);if(minus){event.preventDefault();const itemId=Number(minus.dataset.menuMinus),entry=cart.find(item=>item.id===itemId);if(entry){entry.qty--;if(entry.qty<1)cart=cart.filter(item=>item.id!==itemId);saveCart();renderCart();syncMenuQuantities()}}if(plus){event.preventDefault();const itemId=Number(plus.dataset.menuPlus),entry=cart.find(item=>item.id===itemId);if(entry){entry.qty++;saveCart();renderCart();syncMenuQuantities()}}});
document.addEventListener('click',event=>{const button=event.target.closest('.menu-add');if(button&&!button.onclick){addItem(restaurants.find(restaurant=>(restaurant.menu||[]).some(item=>item.id===Number(button.dataset.item))),Number(button.dataset.item));setTimeout(syncMenuQuantities,0)}});
function openMenu(id){window.location.assign(`/restaurant/${encodeURIComponent(id)}/menu`);}

/* Populate the header with the signed-in customer's saved addresses. */
async function setupCustomerAddressDropdown() {
    const location = document.querySelector('.location');
    const label = document.querySelector('#locationLabel');
    if (!location || !label || !authToken()) return;

    try {
        const response = await fetch('/api/auth/me', {headers: {Authorization: `Bearer ${authToken()}`}});
        if (!response.ok) return;
        const account = (await response.json()).account || {};
        const addresses = Array.isArray(account.addresses) ? account.addresses : [];
        const savedId = localStorage.getItem('tastekart-selected-address-id');
        const savedLabel = localStorage.getItem('tastekart-selected-address-label');
        const selected = addresses.find(address => address.id === savedId) || addresses.find(address => address.label === savedLabel) || addresses[addresses.length - 1];
        if (selected) {
            label.textContent = selected.label || selected.full_address;
            window.tastekartSelectedAddress = selected;
            localStorage.setItem('tastekart-selected-address-id', selected.id);
            localStorage.setItem('tastekart-selected-address-label', selected.label || 'Saved address');
        }

        const menu = document.createElement('div');
        menu.className = 'location-menu';
        menu.setAttribute('role', 'menu');
        menu.innerHTML = addresses.length ? addresses.map(address => `<button type="button" class="location-option" role="menuitem" data-address-id="${escapeHtml(address.id)}"><strong>${escapeHtml(address.label || 'Saved address')}</strong><span>${escapeHtml(address.full_address)}</span></button>`).join('') : '<div class="location-empty">No saved addresses yet.</div>';
        location.appendChild(menu);
        location.setAttribute('tabindex', '0');
        location.setAttribute('aria-haspopup', 'true');
        location.setAttribute('aria-expanded', 'false');

        const closeMenu = () => {
            location.classList.remove('open');
            location.setAttribute('aria-expanded', 'false');
        };
        location.addEventListener('click', event => {
            if (!event.target.closest('.location-option')) {
                location.classList.toggle('open');
                location.setAttribute('aria-expanded', String(location.classList.contains('open')));
            }
        });
        location.addEventListener('keydown', event => {
            if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault();
                location.classList.toggle('open');
                location.setAttribute('aria-expanded', String(location.classList.contains('open')));
            }
            if (event.key === 'Escape') closeMenu();
        });
        menu.querySelectorAll('.location-option').forEach(option => option.addEventListener('click', event => {
            event.stopPropagation();
            const address = addresses.find(item => item.id === option.dataset.addressId);
            if (!address) return;
            label.textContent = address.label || address.full_address;
            window.tastekartSelectedAddress = address;
            localStorage.setItem('tastekart-selected-address-id', address.id);
            localStorage.setItem('tastekart-selected-address-label', address.label || 'Saved address');
            closeMenu();
        }));
        document.addEventListener('click', event => {
            if (!location.contains(event.target)) closeMenu();
        });
    } catch (_) {
        /* Keep the default header label when the account request is unavailable. */
    }
}

setupCustomerAddressDropdown();
