let cart = JSON.parse(localStorage.getItem('tastekart-cart') || '[]');
const $ = selector => document.querySelector(selector);
const money = value => `₹${Number(value).toLocaleString('en-IN')}`;
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
function saveCart() { localStorage.setItem('tastekart-cart', JSON.stringify(cart)); }
function dishVisual(item) { return item.image_url ? `<span class="cart-page-thumb"><img src="${escapeHtml(item.image_url)}" alt="${escapeHtml(item.name)}"/></span>` : `<span class="cart-page-thumb">${escapeHtml(item.emoji || '🍽️')}</span>`; }
function renderCartPage() { const count = cart.reduce((sum, item) => sum + item.qty, 0); const subtotal = cart.reduce((sum, item) => sum + Number(item.price) * item.qty, 0); const fee = subtotal ? 29 : 0; $('#cartRestaurant').textContent = cart[0]?.restaurant || 'Add something delicious from a restaurant near you'; $('#cartPageSubtotal').textContent = money(subtotal); $('#cartPageFee').textContent = money(fee); $('#cartPageTotal').textContent = money(subtotal + fee); $('#cartPageItems').innerHTML = cart.length ? cart.map((item, index) => `<div class="cart-page-row">${dishVisual(item)}<div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.restaurant)} · ${money(item.price)}</p></div><div class="cart-page-qty"><button data-minus="${index}">−</button><strong>${item.qty}</strong><button data-plus="${index}">+</button></div></div>`).join('') : '<div class="cart-page-empty">Your cart is waiting for something delicious.<br/><a href="/">Explore restaurants →</a></div>'; document.querySelectorAll('[data-minus]').forEach(button => button.onclick = () => changeQty(Number(button.dataset.minus), -1)); document.querySelectorAll('[data-plus]').forEach(button => button.onclick = () => changeQty(Number(button.dataset.plus), 1)); }
function changeQty(index, delta) { cart[index].qty += delta; if (cart[index].qty < 1) cart.splice(index, 1); saveCart(); renderCartPage(); }
$('#cartPageCheckout').onclick = () => { if (!cart.length) return; window.location.href = localStorage.getItem('tastekart-auth-token') ? '/' : '/login'; };
renderCartPage();
async function placeCartOrder() { if (!cart.length) return; if (!localStorage.getItem('tastekart-auth-token')) return window.location.href = '/login'; try { const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('tastekart-auth-token')}` }, body: JSON.stringify({ items: cart.map(item => ({ id: item.id, quantity: item.qty })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not place order'); const payment = await fetch(`/api/payments/${data.order.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('tastekart-auth-token')}` }, body: JSON.stringify({ method: 'upi' }) }); if (!payment.ok) throw new Error('Payment could not be completed'); localStorage.removeItem('tastekart-cart'); window.location.href = `/congratulations?order=${encodeURIComponent(data.order.id)}`; } catch (error) { alert(error.message); } } $('#cartPageCheckout').onclick = placeCartOrder;
