FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install --no-cache-dir -r backend/requirements.txt

COPY backend ./backend

EXPOSE 3002

CMD ["uvicorn", "backend.services.user_service.main:app", "--host", "0.0.0.0", "--port", "3002"]
