const $ = selector => document.querySelector(selector);
const token = () => localStorage.getItem('tastekart-admin-token') || '';
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function request(url, options = {}) { const headers = {'Content-Type':'application/json', ...(options.headers || {})}; if (token()) headers.Authorization = `Bearer ${token()}`; const response = await fetch(url, {...options, headers}); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Something went wrong'); return data; }
function showLogin(message = '') { $('#adminAuth').hidden = false; $('#adminMessage').textContent = message; }
function renderRestaurants(restaurants) { $('#adminStats').innerHTML = `<div><span>Onboarded restaurants</span><strong>${restaurants.length}</strong></div><div><span>Open for orders</span><strong>${restaurants.filter(row => row.is_open).length}</strong></div><div><span>Partner accounts</span><strong>${new Set(restaurants.map(row => row.partner?.email).filter(Boolean)).size}</strong></div>`; $('#restaurantList').innerHTML = restaurants.length ? restaurants.map(row => `<article class="restaurant-card"><div class="restaurant-image">${row.image_url ? `<img src="${escapeHtml(row.image_url)}" alt=""/>` : escapeHtml((row.name || 'R').slice(0, 1).toUpperCase())}</div><div class="restaurant-info"><h3>${escapeHtml(row.name)}</h3><p>${escapeHtml(row.cuisine || 'Cuisine not provided')}</p><small>Partner: ${escapeHtml(row.partner?.name || 'Unknown')} · ${escapeHtml(row.partner?.email || 'No email')}</small></div><span class="status ${row.is_open ? 'open' : 'closed'}">${row.is_open ? 'Open' : 'Closed'}</span></article>`).join('') : '<div class="empty-state">No partner restaurants have been onboarded yet.</div>'; }
async function loadAdmin() { try { const identity = await request('/api/auth/me'); if (identity.role !== 'admin') throw new Error('Admin login required'); $('#adminAuth').hidden = true; $('#adminLogout').hidden = false; $('#adminName').textContent = identity.account.name; const data = await request('/api/admin/restaurants'); renderRestaurants(data.restaurants); } catch (error) { localStorage.removeItem('tastekart-admin-token'); showLogin(error.message === 'Admin login required' ? '' : error.message); } }
$('#adminLoginForm').onsubmit = async event => { event.preventDefault(); try { const response = await request('/api/admin/auth/login', {method:'POST',body:JSON.stringify({email:$('#adminEmail').value,password:$('#adminPassword').value})}); localStorage.setItem('tastekart-admin-token', response.token); await loadAdmin(); } catch (error) { showLogin(error.message); } };
$('#adminLogout').onclick = () => { localStorage.removeItem('tastekart-admin-token'); location.reload(); };
$('#refreshAdmin').onclick = loadAdmin;
loadAdmin();
